services:
  - type: web
    name: prono4daysbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN_HERE
      - key: PORT
        value: 10000
